baseurl = "https://jiulongw.github.io"
languageCode = "en-us"
title = "Born to Learn"
theme = "hemingway"
disqusShortname = "jiulongw"
googleAnalytics = "UA-86115491-1"
paginate = 10
copyright = "&copy; <a href=\"https://jiulongw.github.io\">jiulongw</a> 2016"

[taxonomies]
tag = "tags"

[params]

[params.highlight]
style = "github"
languages = ["ruby", "bash"]

[[params.social]]
url = "https://github.com/jiulongw"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/jiulongw"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

